/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class kom_geometry_core_jni */

#ifndef _Included_kom_geometry_core_jni
#define _Included_kom_geometry_core_jni
#ifdef __cplusplus
extern "C" {
#endif

#include "jni.h"
#include "gpc.h"

/*
 * Class:     kom_geometry_core_jni
 * Method:    GeometryTransfer_create
 * Signature: (III[I[[D)J
 */
JNIEXPORT jlong JNICALL Java_kom_geometry_core_jni_GeometryTransfer_1create
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jobjectArray);

/*
 * Class:     kom_geometry_core_jni
 * Method:    GeometryTransfer_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kom_geometry_core_jni_GeometryTransfer_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kom_geometry_core_jni
 * Method:    GeometryTransfer_extract
 * Signature: (J)[Lcom/komelgman/geometry/Geometry;
 */
JNIEXPORT jobjectArray JNICALL Java_kom_geometry_core_jni_GeometryTransfer_1extract
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kom_geometry_core_jni
 * Method:    Gpc_polygonClip
 * Signature: (IJJZ)J
 */
JNIEXPORT jlong JNICALL Java_kom_geometry_core_jni_Gpc_1polygonClip
  (JNIEnv *, jclass, jint, jlong, jlong, jboolean);

/*
 * Class:     kom_geometry_core_jni
 * Method:    Gpc_triangulate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_kom_geometry_core_jni_Gpc_1triangulate
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
